version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    graphite_data: {}
    grafana_data: {}
    prometheus_data: {}

services:
    collectd:
       #image: alpine-collectd:0.0.1
       image: centos-collectd:0.0.1
       container_name: collectd
       volumes:
          - /:/hostfs:ro
       #Enable port for write_prometheus plugin
       ports:
          - "9103:9103"
       environment:
          - GRAPHITE_HOST=graphite
       depends_on:
          - graphite
       networks:
         - monitor-net

    #Enable prometheus for write_prometheus plugin
    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./prometheus:/etc/prometheus
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--storage.tsdb.retention.time=200h'
        - '--web.enable-lifecycle'
      restart: unless-stopped
      ports:
        - "9090:9090"
      networks:
          - monitor-net
    graphite:
        image: graphiteapp/graphite-statsd
        container_name: graphite
        restart: unless-stopped
        ports:
            - "80:80"
            - "2003-2004:2003-2004"
            - "2023-2024:2023-2024"
            - "8125:8125/udp"
            - "8126:8126"
        volumes:
            - graphite_data:/opt/graphite/storage/whisper
        networks:
          - monitor-net

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: unless-stopped
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        networks:
          - monitor-net